agents:
  deepcoder:
    name: "DeepCoder 14B"
    backend_image: "deepcoder:14b"
    description: "Advanced AI coding assistant specialized for software development (Primary Agent)"
    capabilities:
      coding: true
      general_qa: true
      file_operations: true
      streaming: true
    parameters:
      temperature: 0.1
      num_ctx: 16384
      num_predict: 2048
      repeat_penalty: 1.1
      top_k: 40
      top_p: 0.9
    tools:
      - write_file
      - read_file
      - append_file
      - list_files
      - delete_file
      - copy_file
      - create_project
      - get_system_info
      - generate_documentation
      - run_python
      - fetch_url
      - duck_search
      - analyze_repo_structure
      - analyze_repo_languages
      - analyze_repo_directories
    system_message: |
      You are DeepCoder, an advanced AI coding assistant.
